base_url = "https://jesse.cafe"
author = "Jesse Falzone"
compile_sass = true
build_search_index = false
minify_html = false
generate_feed = true
ignored_content = ["*.{jpg,jpeg,png,gif}"]
taxonomies = [
  { name = "tags", feed = true },
]

[link_checker]
skip_prefixes = [
    "https://www.linkedin.com",
    "https://radar.cloudflare.com"
]

[markdown]
highlight_code = false

[extra]
site_name = "jesse.cafe"
